# Generated by Django 5.2.12 on 2026-05-02 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supabase_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('AUTHOR', 'Author'), ('ADMIN', 'Admin')], default='STUDENT', max_length=10)),
                ('university', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_docs_url', models.URLField(blank=True, help_text='URL to uploaded verification documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
