# Generated by Django 5.2.12 on 2026-05-02 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questions', models.JSONField(default=list)),
                ('timer_limit', models.PositiveIntegerField(default=30, help_text='Timer limit in minutes')),
                ('passing_score', models.PositiveSmallIntegerField(default=60, help_text='Passing percentage')),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_set', to='materials.material')),
            ],
            options={
                'verbose_name': 'MCQ Test Set',
                'verbose_name_plural': 'MCQ Test Sets',
            },
        ),
        migrations.CreateModel(
            name='MCQAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict, help_text='Map of question_id to selected_answer')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('time_taken', models.PositiveIntegerField(default=0, help_text='Time taken in seconds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.mcq')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_attempts', to='accounts.profile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
