# Generated by Django 5.2.12 on 2026-05-02 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('PDF', 'PDF E-book'), ('VIDEO', 'Video Lesson'), ('MCQ', 'MCQ Test Set')], max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('file_path', models.CharField(blank=True, help_text='Path in Supabase private bucket', max_length=1000)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Public thumbnail URL')),
                ('university', models.CharField(blank=True, db_index=True, max_length=255)),
                ('course', models.CharField(blank=True, db_index=True, max_length=255)),
                ('semester', models.CharField(blank=True, db_index=True, max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='materials.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['university', 'semester'], name='materials_m_univers_e3f802_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['type', 'is_approved'], name='materials_m_type_e80140_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialreview',
            unique_together={('material', 'user')},
        ),
    ]
